services:
  - type: web
    name: sg-crm-v1
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: PORT
        value: "8000"
      - key: SECRET_KEY
        value: "your-super-secret-jwt-key-change-this-in-production-min-256-bits"
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: DATABASE_URL
        value: "mongodb://localhost:27017"
      - key: DATABASE_NAME
        value: "crm_estimating_db"
  
  - type: web
    name: sg-crm-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
